require('./player-test.js');
require('./point-test.js');
require('./vector-test.js');
require('./edge-test.js');
require('./face-test.js');
require('./obstacle-test.js');
require('./collision-sphere-test.js');
require('./mine-test.js');
require('./booty-test.js');
